spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: user_db
      port: 27017
      host: localhost
      auto-index-creation: true
  shell:
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework8.strelkov.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    ROOT: ERROR

