spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"
application:
  locale: ru_RU
  questions-file-path-en: "questions_en.csv"
  questions-file-path-ru: "questions_ru.csv"
  exam-passing-score: 3